---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: 'GitHub2Gerrit Python'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      preserve_github_prs:
        description: "Do NOT close GitHub PRs after pushing to Gerrit"
        required: false
        default: false
        type: boolean
      allow_duplicates:
        description: "Allow duplicate changes to be raised in Gerrit"
        required: false
        default: false
        type: boolean

  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.run_id }}"
  cancel-in-progress: true

jobs:
  github2gerrit:
    name: 'GitHub2Gerrit Python'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    timeout-minutes: 12
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2  # v2.13.2
        name: 'Harden runner'
        with:
          egress-policy: audit

      - name: 'Checkout repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 10
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: 'Run GitHub2Gerrit Action'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/github2gerrit-action@d325efbed2a65580e481ca3841528be16cf5e87a  # v1.0.1
        with:
          USE_PR_AS_COMMIT: true
          ALLOW_DUPLICATES: ${{ inputs.allow_duplicates }}
          PRESERVE_GITHUB_PRS: ${{ inputs.preserve_github_prs }}
          GERRIT_SSH_PRIVKEY_G2G: ${{ secrets.GERRIT_SSH_PRIVKEY_G2G }}
          GERRIT_KNOWN_HOSTS: ${{ vars.GERRIT_KNOWN_HOSTS }}
          VERBOSE: true
